### ISSUE TITLE
cubids-group crashes when BIDS directory contains derivatives

### ISSUE THREAD

**Issue by surchs** [PennLINC/CuBIDS#127]
Hi, I have been trying out cubids-group with some BIDS example data from the [example repo](https://github.com/bids-standard/bids-examples).

I noticed that if a BIDS directory contains a derivatives folder, cubids-group crashes.
Example:
This
```
cubids-group ../bids-examples/ds001  d1 
```
works well. But this
```
cubids-group ../bids-examples/synthetic/ synth
```

<details>
  <summary>crashes with filepath error</summary>
  
  ```bash
➜ cubids-group ../bids-examples/synthetic/ synth               
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/surchs/Repositories/Sandbox/CuBIDS/venv/bin/cubids-group", line 11, in <module>
    load_entry_point('cubids==0.1.0', 'console_scripts', 'cubids-group')()
  File "/home/surchs/Repositories/Sandbox/CuBIDS/venv/lib/python3.8/site-packages/cubids-0.1.0-py3.8.egg/cubids/cli.py", line 279, in cubids_group
    bod.get_CSVs(str(opts.output_prefix),)
  File "/home/surchs/Repositories/Sandbox/CuBIDS/venv/lib/python3.8/site-packages/cubids-0.1.0-py3.8.egg/cubids/cubids.py", line 891, in get_CSVs
    big_df, summary = self.get_param_groups_dataframes()
  File "/home/surchs/Repositories/Sandbox/CuBIDS/venv/lib/python3.8/site-packages/cubids-0.1.0-py3.8.egg/cubids/cubids.py", line 733, in get_param_groups_dataframes
    self.get_param_groups_from_key_group(key_group)
  File "/home/surchs/Repositories/Sandbox/CuBIDS/venv/lib/python3.8/site-packages/cubids-0.1.0-py3.8.egg/cubids/cubids.py", line 709, in get_param_groups_from_key_group
    if mod in filepath:
UnboundLocalError: local variable 'filepath' referenced before assignment

  ```
</details>

Other cubids tools like `cubids-print-metadata-fields` work fine with BIDS+derivatives folder. 

## Setup
- cloned current master
- `Linux host 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- installed CuBids via `setup.py`

<details>
  <summary>pip freeze</summary>

```
annexremote==1.5.0
appdirs==1.4.4
bids-validator==1.7.3.dev0
boto==2.49.0
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
click==8.0.1
cryptography==3.4.7
cubids==0.1.0
datalad==0.14.6
Deprecated==1.2.12
distro==1.5.0
docopt==0.6.2
fasteners==0.16.3
future==0.18.2
humanize==3.10.0
idna==2.10
importlib-metadata==4.6.1
iso8601==0.1.14
jeepney==0.6.0
joblib==1.0.1
jsmin==2.2.2
keyring==23.0.1
keyrings.alt==4.0.2
msgpack==1.0.2
nibabel==3.2.1
num2words==0.5.10
numpy==1.21.0
packaging==21.0
pandas==1.3.0
patool==1.12
patsy==0.5.1
pybids==0.13.1
pycparser==2.20
PyGithub==1.55
PyJWT==2.1.0
PyNaCl==1.4.0
pyparsing==3.0.0b2
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
scikit-learn==0.24.2
scipy==1.7.0
SecretStorage==3.3.1
simplejson==3.17.2
six==1.16.0
sklearn==0.0
SQLAlchemy==1.3.24
threadpoolctl==2.1.0
tqdm==4.61.2
urllib3==1.26.6
Whoosh==2.7.4
wrapt==1.12.1
zipp==3.5.0
```

</details>

I haven't explored further

**Comment by scovitz** [comment]
Hi! 

So glad you're using CuBIDS! Thanks for the feedback. I agree that we should be supporting bids directories that contain derivatives folders and am opening a PR for that now.

Best,
Sydney Covitz
