### ISSUE TITLE
deploy_pypi job is failing

### ISSUE THREAD

**Issue by tsalo** [PennLINC/CuBIDS#280]
The error is:

> ERROR Source /tmp/src/CuBIDS does not appear to be a Python project: no pyproject.toml or setup.py

**Comment by tsalo** [comment]
It's still failing:

```
Enter your username: Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/__main__.py", line 51, in <module>
    sys.exit(main())
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/commands/upload.py", line 198, in main
    return upload(upload_settings, parsed_args.dists)
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/commands/upload.py", line 127, in upload
    repository = upload_settings.create_repository()
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/settings.py", line 329, in create_repository
    self.username,
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/settings.py", line 131, in username
    return cast(Optional[str], self.auth.username)
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/auth.py", line 34, in username
    return utils.get_userpass_value(
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/utils.py", line 248, in get_userpass_value
    value = prompt_strategy()
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/auth.py", line 85, in username_from_keyring_or_prompt
    return self.prompt("username", input)
  File "/opt/circleci/.pyenv/versions/3.10.2/lib/python3.10/site-packages/twine/auth.py", line 96, in prompt
    return how(f"Enter your {what}: ")
EOFError
```
