### ISSUE TITLE
RU site pipeline output error

### ISSUE THREAD

**Issue by BaranMary** [PennLINC/CuBIDS#296]
## Summary

Hello,
We are currently conducting a revised audit outputs of our abcd-hcp-pipeline for the HBN site (RU). However, we have encountered a limitation wherein we only receive structural outputs and a single rest run output, unlike the other two sites that do not experience this issue. When using the original audit script, the following error occurs:
```
Traceback (most recent call last):
  File "/panfs/jay/groups/6/faird/shared/projects/new_rae_testing/abcd-hcp-pipeline_audit/run.py", line 128, in <module>
    sessions_to_analyze = [item['Prefix'].split('/')[2] for item in get_data if 'ses' in item['Prefix'].split('/')[2]]
  File "/panfs/jay/groups/6/faird/shared/projects/new_rae_testing/abcd-hcp-pipeline_audit/run.py", line 128, in <listcomp>
    sessions_to_analyze = [item['Prefix'].split('/')[2] for item in get_data if 'ses' in item['Prefix'].split('/')[2]]
TypeError: string indices must be integers
```
We appreciate your help and consideration

## Additional details

- CuBIDS version:
- Datalad version:

**Comment by tsalo** [comment]
@BaranMary sorry, but your traceback doesn't seem to be related to CuBIDS code. Could you provide a bit more detail? I also don't know what you mean by "audit script".

**Comment by tsalo** [comment]
We never got a follow-up so I'm going to close this. @BaranMary if you are still struggling with this and it appears to be CuBIDS-related, please reopen this issue or open a new one.

**Comment by BaranMary** [comment]
Hello
Thanks for your email.
The issue was resolved and sorry I forgot to follow up here. That's correct
that it wasn't related to CuBIDS format.
Thank you very much!
