### ISSUE TITLE
what is the correct usage of cubids apply?

### ISSUE THREAD

**Issue by jhauneuro** [PennLINC/CuBIDS#314]
## Summary
Hello,

I got the following error when trying to use the cubids apply command. What is the correct syntax for this command?

Thanks,
Jan

## Additional details

- CuBIDS version: 1.1.0
- Datalad version: n/a

### What were you trying to do?
Run cubids apply.

### What did you expect to happen?
Apply changes specified in edited_summary.tsv file to my bids directory.

### What actually happened?
Returned an error.

## Reproducing the bug

```
cubids apply bids_dir bids_dir/code/CuBIDS/v0_edited_summary.tsv bids_dir/code/CuBIDS/v0_files.tsv v1
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cubids/bin/cubids", line 8, in <module>
    sys.exit(_main())
  File "/opt/anaconda3/envs/cubids/lib/python3.8/site-packages/cubids/cli.py", line 697, in _main
    options.func(**args)
TypeError: apply() missing 2 required positional arguments: 'edited_tsv_prefix' and 'output_prefix'

```

**Comment by jmschabdach** [comment]
Also encountered this same bug in 1.1.0. After manually adding a `print(args)` to the `cli.py` file, I get the following (redacted) output:

```
{'bids_dir': PosixPath('/path/to/BIDS'), 'edited_summary_tsv': PosixPath('/path/to/BIDS/code/CuBIDS/run01_summary.tsv'), 'files_tsv': PosixPath('/path/to/BIDS/code/CuBIDS/run01_files.tsv'), 'new_tsv_prefix': PosixPath('run02'), 'use_datalad': False, 'container': None, 'acq_group_level': 'subject', 'config': PosixPath('/path/to/config.yml'), 'func': <function apply at 0x7fa1b32ddf70>}
Traceback (most recent call last):
  File "/home/youngjm/miniconda3/envs/cubids-v03/bin/cubids", line 8, in <module>
    sys.exit(_main())
  File "/home/youngjm/miniconda3/envs/cubids-v03/lib/python3.8/site-packages/cubids/cli.py", line 698, in _main
    options.func(**args)
TypeError: apply() missing 2 required positional arguments: 'edited_tsv_prefix' and 'output_prefix'
```

(@tsalo)
